networks:
  homelab:
    name: homelab
    external: true
  droposs:

services:
  postgres:
    image: postgres:14-alpine
    networks:
      - droposs
    healthcheck:
      test: pg_isready -d drop -U drop
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=drop
      - POSTGRES_USER=drop
      - POSTGRES_DB=drop

  drop:
    container_name: droposs
    image: decduck/drop-oss:v0.2.0-beta
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - droposs
      - homelab
    volumes:
      - ${LIBRARY_PATH}:/library
      - ./certs:/certs
      - ./objects:/objects
    env_file: .env
