- name: Home
  width: slim
  center-vertically: true
  columns:
    - size: small
      widgets:
        - type: dns-stats
          service: pihole-v6
          url: https://pihole.fntz.net/
          password: supersecretapppassword

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed
        - type: server-stats
          servers:
            - type: local
              name: Jade

    - size: full
      widgets:
        - type: search
          search-engine: google

        - type: monitor
          title: Services
          cache: 1m
          sites:
            - title: Plex
              url: https://plex.fntz.net/web/index.html#/
              icon: si:plex
            - title: Tautulli
              url: https://tt.fntz.net/
              icon: di:tautulli
            - title: Immich
              url: https://img.fntz.net
              icon: di:immich
            - title: NZBGet
              url: https://nzb.fntz.net
              icon: di:nzbget
            - title: Proxy
              url: https://proxy.fntz.net
              icon: di:nginx-proxy-manager
            - title: Nextcloud
              url: https://cloud.fntz.net
              icon: di:nextcloud
            - title: PiHole
              url: https://pihole.fntz.net/admin
              icon: di:pi-hole
            - title: Vaultwarden
              url: https://vw.fntz.net
              icon: di:vaultwarden
            - title: Overseerr
              url: https://overseerr.fntz.net
              icon: di:overseerr
            - title: Dozzle
              url: https://dz.fntz.net
              icon: di:dozzle

        - type: monitor
          title: Servarr
          cache: 1m
          sites:
            - title: Radarr
              url: https://radarr.fntz.net
              icon: di:radarr
            - title: Sonarr
              url: https://sonarr.fntz.net
              icon: di:sonarr
            - title: Lidarr
              url: https://lidarr.fntz.net
              icon: di:lidarr
