- name: Home
  width: slim
  center-vertically: true
  columns:
    - size: small
      widgets:
        - type: dns-stats
          service: pihole-v6
          url: https://pihole.fntz.net/
          password: ${PIHOLE_TOKEN}
        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://selfh.st/rss/
              title: selfh.st
            - url: https://ciechanow.ski/atom.xml
            - url: https://www.joshwcomeau.com/rss.xml
              title: Josh Comeau
            - url: https://samwho.dev/rss.xml
            - url: https://ishadeed.com/feed.xml
              title: Ahmad Shadeed
        - type: server-stats
          servers:
            - type: local
              name: Jade

    - size: full
      widgets:
        - type: search
          search-engine: google

        - type: monitor
          title: Services
          cache: 1m
          sites:
            - title: Plex
              url: https://plex.fntz.net/web/index.html#/
              icon: si:plex
            - title: Jellyfin
              url: https://jf.fntz.net
              icon: si:jellyfin
            - title: Tautulli
              url: https://tt.fntz.net/
              icon: di:tautulli
            - title: HDHomeRun
              url: http://172.16.0.42
              icon: di:hdhomerun
            - title: Immich
              url: https://img.fntz.net
              check-url: http://immich_server:2283
              icon: di:immich
            - title: NZBGet
              url: https://nzb.fntz.net
              icon: di:nzbget
            - title: Frigate
              url: https://nvr.fntz.net
              check-url: http://${VIDEO_MACHINE}:5000
              icon: di:frigate
            - title: Nextcloud
              url: https://cloud.fntz.net
              icon: di:nextcloud
            - title: PiHole
              url: https://pihole.fntz.net/admin
              icon: di:pi-hole
            - title: Vaultwarden
              url: https://vw.fntz.net
              icon: di:vaultwarden
            - title: Overseerr
              url: https://overseerr.fntz.net
              icon: di:overseerr
            - title: Dozzle
              url: https://dz.fntz.net
              check-url: http://dozzle:8080
              icon: di:dozzle
            - title: Gitea
              url: https://git.fntz.net
              icon: di:gitea
            - title: Code Server
              url: https://code.fntz.net
              check-url: http://code-server:8443
              icon: di:visual-studio-code
            - title: HomeBridge
              url: https://bridge.fntz.net
              icon: di:homebridge
            - title: Excalidraw
              url: https://draw.fntz.net
              icon: di:excalidraw
            - title: CUPS
              url: https://print.fntz.net
              icon: di:cups
            - title: Dashdot
              url: https://stats.fntz.net
              icon: di:dashdot.png
            - title: Grafana
              url: https://graf.fntz.net
              icon: si:grafana
            - title: Panel
              url: https://panel.fntz.net
              icon: di:pelican-panel
            - title: TrueNAS
              url: https://nas.fntz.net
              icon: si:truenas

        - type: monitor
          title: Servarr
          cache: 1m
          sites:
            - title: Radarr
              url: https://radarr.fntz.net
              check-url: http://radarr:7878
              icon: di:radarr
            - title: Sonarr
              url: https://sonarr.fntz.net
              check-url: http://sonarr:8989
              icon: di:sonarr
            - title: Lidarr
              url: https://lidarr.fntz.net
              check-url: http://lidarr:8686
              icon: di:lidarr
