networks:
  homelab:
    name: homelab
    external: true

services:
  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file: .env
    command:
      "--token=${TUNNEL_TOKEN}"
    networks:
      - homelab