networks:
  homelab:
    name: homelab
    external: true

services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
    env_file: .env