networks:
  homelab:
    name: homelab
    external: true

services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./data:/data
      - ./config:/etc/caddy
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - homelab
    env_file: .env

  tinyauth:
    container_name: tinyauth
    image: ghcr.io/steveiliop56/tinyauth:v3
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - APP_URL=http://auth.fntz.net
      - SECRET=${TINYAUTH_SECRET}
      - USERS=${TINYAUTH_USER}