networks:
  homelab:
    name: homelab
    external: true

services:
  dashdot:
    container_name: dashdot
    image: 'mauricenino/dashdot'
    volumes:
      - /:/mnt/host:ro
    restart: always
    networks:
      - homelab
