networks:
  homelab:
    name: homelab
    external: true

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    env_file: .env
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - homelab