networks:
  homelab:
    name: homelab
    external: true

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    networks:
      - homelab
