networks:
  homelab:
    name: homelab
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /path/to/tv/share:/data/tvshows
      - /path/to/movie/share:/data/movies
      - /path/to/music/share:/data/music
    restart: unless-stopped
    networks:
      - homelab
