networks:
  homelab:
    name: homelab
    external: true

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file: .env
    volumes:
      - ./config:/config
      - ${TV_PATH}:/data/tvshows
      - ${MOVIE_PATH}:/data/movies
      - ${MUSIC_PATH}:/data/music
    restart: unless-stopped
    networks:
      - homelab
