version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATION_URL=discord://webhook_secret@channel_id
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
