networks:
  homelab:
    name: homelab
    external: true

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw
    restart: unless-stopped
    networks:
      - homelab