services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:gluetun"
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - ${DOWNLOADS_FOLDER}:/downloads
    restart: unless-stopped