networks:
  homelab:
    name: homelab
    external: true

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    networks:
      - homelab
    volumes:
      - ./config:/config
      - ${DATA_PATH}:/data
    restart: unless-stopped
