networks:
  homelab:
    name: homelab
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    volumes:
      - ./sonarr_config:/config
      - ${MEDIA_PATH}:/data
      - ${MEDIA_PATH}/Downloads:/downloads
    restart: always
    networks:
      - homelab
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    restart: always
    env_file: .env
    volumes:
      - ./radarr_config:/config
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH}/Downloads:/downloads
    networks:
      - homelab
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    restart: always
    env_file: .env
    volumes:
      - ./lidarr_config:/config
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH}/Downloads:/downloads
    networks:
      - homelab