version: '3.3'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - /path/to/media/share:/data
      - /path/to/nzbget/downloads:/downloads
    ports:
      - 8989:8989
    restart: always
