volumes:
  config:
networks:
  homelab:
    name: homelab
    external: true

services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    env_file: .env
    volumes:
      - config:/config
      - ${DOWNLOADS_PATH}:/downloads
    restart: always
    networks:
      - homelab
