networks:
  homelab:
    name: homelab
    external: true
volumes:
  app_data:
  letsencrypt:
  database:

services:
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./db:/var/lib/mysql

  app:
    image: 'jc21/nginx-proxy-manager:2.12.3'
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - letsencrypt:/etc/letsencrypt
      - ./98-themepark:/etc/cont-init.d/98-themepark
    networks:
      - homelab
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
      TP_THEME: 'dracula'

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v3
    container_name: tinyauth
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - SECRET=aaaaaBBBBBccccccDDDDD
      - APP_URL=https://auth.example.com
      - USERS=blablablabla