networks:
  homelab:
    name: homelab
    external: true

services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "${MUSIC_PATH}:/music:ro"
    networks:
      - homelab
