networks:
  homelab:
    name: homelab
    external: true

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    networks:
      - homelab
