networks:
  homelab:
    name: homelab
    external: true

services:
  cup:
    image: ghcr.io/sergi0g/cup
    container_name: cup
    command: serve
    restart: unless-stopped
    networks:
     - homelab
  