networks:
  homelab:
    name: homelab
    external: true

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeserver
    env_file: .env
    volumes:
      - ./config:/config
      - ../../Docker:/config/workspace/docker # my docker configurations
    restart: unless-stopped
    networks:
      - homelab
