version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: "unless-stopped"
    user: 1000:1000

    ports:
      - 9090:9090

    volumes:
      - ./config:/etc/prometheus
      - ./data:/prometheus
