networks:
  homelab:
    name: homelab
    external: true
  nextcloud:
    name: nextcloud

services:
  db:
    container_name: nc_postgresql
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - nextcloud

  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    links:
      - db
    volumes:
      - ./data:/var/www/html
    env_file: .env
    networks:
      - homelab
      - nextcloud
