volumes:
  data:
    external: true
    name: nextcloud_data
  db:
    external: true
    name: nextcloud_db

networks:
  homelab:
    name: homelab
    external: true
  nextcloud:
    name: nextcloud

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    networks:
      - nextcloud

  app:
    container_name: nextcloud
    image: nextcloud
    restart: always
    links:
      - db
    volumes:
      - data:/var/www/html
    env_file: .env
    networks:
      - homelab
      - nextcloud