networks:
  homelab:
    name: homelab
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./vw-data/:/data/
    networks:
      - homelab
